#!/bin/bash

function check_first_parameter {
	if [[ ! (-f $1) ]]; then
	    echo "File is missing"
	    exit 1
	fi
}

function check_third_parameter {
	if (( $1 < 1 )); then
	    echo "Illegal or missing parameters"
	    exit 1
	fi
}

function recursive_search {
	if [[ -f "$1" && "$1" == *".flat" ]]; then
		echo `pwd`/"$1"
    fi
    if [[ -d "$1" && "$1" == *".flat" ]]; then
		cd "$1"
		for file in `ls`; do
			recursive_search $file
		done
		cd ..
    fi
}

if (( $# != 1 && $# != 3 )); then
    echo "Illegal or missing parameters"
	exit 1
fi
check_first_parameter $1
if (( $# == 3 )); then
	check_third_parameter $3
fi

city=`echo ${2,,} | cut -d" " -f1-`
city="${city//\ /'5'}"

cat $1 | cleanLines | while read line; do
	recursive_search $line
done | while read line; do
	cat $line | cleanLines
done | handleNamesDates | grep -w $city | sort -sk6 | uniq -1 | sort -nsk6 \
	  | head -n$3 | sort -nsk1 | sort -nsk6 | sort -nrsk8 | cut -d" " -f5-7