#!/bin/bash

function date_to_num {
    for ((i = 0 ; i < 3 ; i++ )); do
		arr[$i]=$( echo $1 | cut -d"." -f$(( $i+1 )) )
	done
    for ((i = 0 ; i < 2 ; i++ )); do
        if [[ arr[$i] =~ ^[1-9]$ ]]; then # <- NO ERROR WITH THIS (octal shit)
         arr[$i]=$( echo 0$(( ${arr[$i]} )) )
        fi
    done
    echo $( echo ${arr[2]}${arr[1]}${arr[0]} )
}

function convert_dates {
    while read -a line; do
        last=$(( ${#line[*]} - 1 ))
        line[$last]=$( date_to_num `echo ${line[$last]}` )
        echo ${line[*]}
    done
    
}

function add_index {
    i=0
    while read -a line; do
        echo $i ${line[*]}
        let i++
    done
}

function underline_names {
    while read -a line; do
        for ((i = 0 ; i < $(( ${#line[*]} - 1 )) ; i++ )); do
            if [[  ${line[i]} != *[0-9]* && ${line[i+1]} != *[0-9]* ]]; then
                echo -n ${line[i],,}'5'
            else
                echo -n ${line[i],,}" " 
            fi
        done
        echo ${line[$(( ${#line[*]} - 1 ))],,}
    done
}

cat $1 | convert_dates | underline_names | add_index